# Generated by Django 4.0.2 on 2022-04-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceitasMacro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
