# Generated by Django 4.0.2 on 2022-04-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceitasMacro', '0002_alter_img_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='receita',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AddField(
            model_name='receita',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='receita', to='ReceitasMacro.Label'),
        ),
    ]
