# Generated by Django 4.0.4 on 2022-05-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceitasMacro', '0003_label_alter_receita_name_receita_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='imgurl',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
