# Generated by Django 4.0.4 on 2022-05-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReceitasMacro', '0004_img_imgurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='imgurl',
        ),
    ]
