# Generated by Django 4.0.4 on 2022-06-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceitasMacro', '0005_remove_img_imgurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='rawingredientes_pt',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
