# Generated by Django 4.0.4 on 2022-06-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceitasMacro', '0006_receita_rawingredientes_pt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='rawingredientes_pt',
            field=models.CharField(max_length=800),
        ),
    ]
