# Generated by Django 4.0.4 on 2022-06-15 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReceitasMacro', '0007_alter_receita_rawingredientes_pt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
